#!/bin/sh

set -e
if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
        db_input high vidalia/info || true
        db_go
fi

#DEBHELPER#
